"""Removed Example, Add craeted_at and deleted_at to BaseCreatedModel for all models that can be created

Revision ID: 3d3ce2e0824d
Revises: 
Create Date: 2025-08-17 15:04:31.391574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d3ce2e0824d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('example')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('example',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('example_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('example_pkey'))
    )
    # ### end Alembic commands ###
